#nstarx.azurecr.io/cost-dashboard-base:latest
FROM python:3.9-slim

WORKDIR /app

# Copy only requirements for dependency installation
COPY requirements.txt .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Set environment for the final image
# ENV PYTHONUNBUFFERED=1
# ENV STREAMLIT_SERVER_PORT=8501
# ENV STREAMLIT_SERVER_ADDRESS=0.0.0.0
# ENV STREAMLIT_SERVER_ENABLE_CORS=false